server:
  port: 8005

spring:
  application:
    name: crash-service
  config:
    import: "optional:nacos:${spring.application.name}.yml"
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: nacos
        password: nacos
        namespace: ${NACOS_NAMESPACE:app-platform}
        group: DEFAULT_GROUP
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: nacos
        password: nacos
        namespace: ${NACOS_NAMESPACE:app-platform}
        group: DEFAULT_GROUP
        file-extension: yml
        shared-configs:
          - data-id: common.yml
            group: DEFAULT_GROUP
            refresh: true
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/crash_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.app.crash.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.app.crash: DEBUG
