spring.application.name=appPlatform
spring.profiles.active=@spring.profiles.active@

mybatis.mapper-locations=classpath*:mapper/**/*.xml
# mybatis.type-aliases-package=com.app.appplatform.entity
# mybatis.configuration.map-underscore-to-camel-case=true
# mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

pagehelper.helper-dialect=mysql
pagehelper.reasonable=true
pagehelper.support-methods-arguments=true
pagehelper.params=count=countSql

spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
app.upload.dir=/app/uploads

jwt.secret=KzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Ng==
jwt.expiration=86400

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.timeout=60000

spring.cache.redis.time-to-live= 3600000

minio.endpoint=http://172.16.110.45:19000/
minio.access-key=minio
minio.secret-key=Rh6SpXFthbZkHRDR
# ?????
minio.bucket.default=configfile
# ?????
minio.bucket.logs=applogs
# app?????
minio.bucket.apps=apps

# ???????8080?
server.port=8080

# Actuator????
management.endpoints.web.base-path=/actuator
# ??????
management.endpoints.web.exposure.include=*
# ????????
management.endpoint.health.show-details=always

rabbitmq.queue.event=app.event.queue
rabbitmq.exchange.event=app.event.exchange
rabbitmq.routing-key.event=app.event.routing

spring.rabbitmq.virtual-host=/
spring.rabbitmq.listener.simple.prefetch=10
spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=10
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=1
spring.rabbitmq.listener.simple.retry.max-interval=1000
spring.rabbitmq.listener.simple.default-requeue-rejected=false

#spring.jackson.time-zone=GMT+8
#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

app.package-name=szyd
app.download-url=https://app.ryyjdjg.cn/appPlatform/download
app.store-package=com.sczl.mb

log.request.timeout-minutes=120
log.request.redis-key=appPlatform-request:
